workflows:
    ios-workflow:
      name: Pulse Monitor
      integrations:
        app_store_connect: HeartRate - API
      environment:
        ios_signing:
          distribution_type: app_store
          bundle_identifier: com.stress.heartrate.app
        vars:
          XCODE_WORKSPACE: "cl.heart.xcworkspace"
          XCODE_SCHEME: "cl.heart"
          APP_STORE_APPLE_ID: 6746779084
        xcode: latest
        cocoapods: default
      scripts:
        - name: Install CocoaPods dependencies
          script: |
            pod install
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:
          auth: integration
          submit_to_testflight: true
          expire_build_submitted_for_review: true
          submit_to_app_store: false